/*
 *  Orca Project: Components for robotics.
 *
 *  Copyright (C) 2004-2006
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 *  $Id$
 */

// Autogenerated by orcasmc which is based on smc by R. Martin.
// See http://www.objectmentor.com/resources/downloads/index.

#ifndef ORCASMC_AUTOGEN_BROWSERFSM_FSM_H
#define ORCASMC_AUTOGEN_BROWSERFSM_FSM_H

#include <IceUtil/Mutex.h>

class BrowserFsm;

class BrowserFsmState 
{
public:
    virtual ~BrowserFsmState() {};
    virtual const char* StateName() const = 0;
    virtual void up(BrowserFsm& s);
    virtual void deactivate(BrowserFsm& s);
    virtual void fault(BrowserFsm& s);
    virtual void reload(BrowserFsm& s);
    virtual void pick(BrowserFsm& s);
    virtual void activate(BrowserFsm& s);
};

class BrowserFsmOperationState : public BrowserFsmState 
{
public:
    virtual const char* StateName() const
        {return("Operation");};
    virtual void deactivate(BrowserFsm&);
    virtual void fault(BrowserFsm&);
    virtual void up(BrowserFsm&);
    virtual void reload(BrowserFsm&);
};

class BrowserFsmInterfaceState : public BrowserFsmState 
{
public:
    virtual const char* StateName() const
        {return("Interface");};
    virtual void deactivate(BrowserFsm&);
    virtual void fault(BrowserFsm&);
    virtual void up(BrowserFsm&);
    virtual void reload(BrowserFsm&);
    virtual void pick(BrowserFsm&);
};

class BrowserFsmComponentState : public BrowserFsmState 
{
public:
    virtual const char* StateName() const
        {return("Component");};
    virtual void deactivate(BrowserFsm&);
    virtual void fault(BrowserFsm&);
    virtual void up(BrowserFsm&);
    virtual void reload(BrowserFsm&);
    virtual void pick(BrowserFsm&);
};

class BrowserFsmRegistryState : public BrowserFsmState 
{
public:
    virtual const char* StateName() const
        {return("Registry");};
    virtual void deactivate(BrowserFsm&);
    virtual void fault(BrowserFsm&);
    virtual void reload(BrowserFsm&);
    virtual void pick(BrowserFsm&);
};

class BrowserFsmIdleState : public BrowserFsmState 
{
public:
    virtual const char* StateName() const
        {return("Idle");};
    virtual void activate(BrowserFsm&);
};

// Human-written FSM should derive from this class
class BrowserFsm
{
    friend class BrowserFsmState;
    friend class BrowserFsmOperationState;
    friend class BrowserFsmInterfaceState;
    friend class BrowserFsmComponentState;
    friend class BrowserFsmRegistryState;
    friend class BrowserFsmIdleState;

public:
    // default constructor sets initial state
    BrowserFsm() : itsState(&IdleState) {};
    virtual ~BrowserFsm() {};

    // anybody can issue events to the FSM
    void up() {itsState->up(*this);}
    void deactivate() {itsState->deactivate(*this);}
    void fault() {itsState->fault(*this);}
    void reload() {itsState->reload(*this);}
    void pick() {itsState->pick(*this);}
    void activate() {itsState->activate(*this);}

protected:
    // Implement these actions in the derived class
    virtual void pickLastOperation() = 0;
    virtual void pickLastInterface() = 0;
    virtual void loadOperation() = 0;
    virtual void pickLastComponent() = 0;
    virtual void loadInterface() = 0;
    virtual void quit() = 0;
    virtual void loadComponent() = 0;
    virtual void loadRegistry() = 0;

    // Overwrite the base implementation if needed.
    virtual void fsmError(const char* t, const char* s);

private:
    BrowserFsmState* itsState;
    BrowserFsmState& GetState() const {return *itsState;};
    void SetState(BrowserFsmState& theState) {itsState=&theState;}
    IceUtil::Mutex mutex_;

    static BrowserFsmOperationState OperationState;
    static BrowserFsmInterfaceState InterfaceState;
    static BrowserFsmComponentState ComponentState;
    static BrowserFsmRegistryState RegistryState;
    static BrowserFsmIdleState IdleState;
};

#endif
