# labelInstall.cmake
# Author Duncan Mercer

# This script is only called during the installation phase.

# When we are installing the system using 'make install'
# we want to label the installation date / time for 
# identification purposes. 

if( FALSE )
if( NOT WIN32 )

  # Specify where to write the information generated by the labelInstall.sh script
  # Note the this is the ./bin/ directory of the install
  set(LABEL_OUTPUT_FILE "${CMAKE_INSTALL_PREFIX}/bin/hydroinstallinfo.txt")

  # Setup the path to the script. Note that this is in our source
  if( SYSTEM_HYDRO_SOURCE )
    set(LABEL_SCRIPT "${SYSTEM_HYDRO_SOURCE}/scripts/shell/labelInstall.sh")  
    message("-- Labeling and time stamping the install")
    EXECUTE_PROCESS(COMMAND ${LABEL_SCRIPT} ${SYSTEM_HYDRO_SOURCE}
                    RESULT_VARIABLE SCRIPT_RESULT
                    OUTPUT_VARIABLE SCRIPT_DATA)
                  
    # Flag it if there was a failure.
    if( ${SCRIPT_RESULT} )              
      message("WARNING: Unable to timestamp the install. Continuing anyway.")
      message("${SCRIPT_DATA}")
    endif( ${SCRIPT_RESULT} )              

    #Write file even if failed above. Ensures that failure gets recorded
    file(WRITE ${LABEL_OUTPUT_FILE} ${SCRIPT_DATA})

  else( SYSTEM_HYDRO_SOURCE )

    file(WRITE ${LABEL_OUTPUT_FILE} "WARNING: var SYSTEM_HYDRO_SOURCE not found Unable to timestamp the install.")
    message("WARNING: variable SYSTEM_HYDRO_SOURCE not found Unable to timestamp the install. Continuing anyway.")
    
  endif( SYSTEM_HYDRO_SOURCE )

  

endif( NOT WIN32 )
endif( FALSE )