#!/bin/sh
#
# Builds all the documentation for Orca2
#
# This consists of the following steps:
#
# 1) Convert all the doxygen comments into html
# 2) Add the header (which contains the Orca sidebar) to both
#    the doxygen-generated html and the human-generated html (in html/raw_html)a
#
################################################################################

USAGE_ARGS=""

#
# Usage: build_doxygen <dir> [<doxyfilename>]
#
build_doxygen () {
    if [ $# -le 0 ]; then
        echo "Require at least one one argument"
        exit 1
    fi
    dir=$1

    if [ $# -eq 2 ]; then
        doxyfile=$2
    fi

    cd $dir

    echo "doxygen $doxyfile"
    doxygen $doxyfile

    res=$?
    if [ $res -ne 0 ]; then
        echo "Problem building doxygen in $dir: $res"
        exit 1
    fi
    cd -
}

#
# First build the doxygen stuff locally
#

echo "build_doxygen . orcadoxyfile"
build_doxygen . orcadoxyfile

#
# Then add the sidebar stuff
#

./format_documentation
