#!/bin/sh
#
# Builds all the documentation for Orca2
#
# This consists of the following steps:
#
# 1) Convert all the doxygen comments into html
# 2) Add the header (which contains the Orca sidebar) to both
#    the doxygen-generated html and the human-generated html (in html/raw_html)a
#
################################################################################

USAGE_ARGS=""

#
# Usage: build_doxygen <dir>
#
build_doxygen () {
    if [ $# -ne 1 ]; then
        echo "Require one argument"
        exit 1
    fi

    dir=$1
    cd $dir

    doxygen
    if [ ! $? ]; then
        echo "Problem building doxygen in $1"
        exit 1
    fi
    cd -
}

#
# Usage: build_slice <dir>
#
build_slice () {
    if [ $# -ne 1 ]; then
        echo "Require one argument"
        exit 1
    fi

    dir=$1

    slice2docbook -s -I$dir/.. html/orca-slice.sgml $dir/*.ice

    if [ ! $? ]; then
        echo "Problem building slice documentation in $1"
        exit 1
    fi

    echo "Please wait...  This may take a while."
    cd html
    docbook-2-html orca-slice.sgml
    if [ ! $? ]; then
        echo "Problem building slice documentation in $1"
        exit 1
    fi
    cd -
}

#
# First build the doxygen stuff locally
#

build_doxygen ../src/utils
build_doxygen ../src/components
build_doxygen ../src/interfaces

#
# Build the slice documentation using slice2cpp
#
#build_slice ../src/interfaces/slice/orca

#
# Then add the sidebar stuff
#

cd html
./format_documentation
cd -