/*
 * Orca-Robotics Project: Components for robotics 
 *               http://orca-robotics.sf.net/
 * Copyright (c) 2008 Alex Makarenko
 *
 * This copy of Orca is licensed to you under the terms described in
 * the LICENSE file included in this distribution.
 *
 */

#include "gen.h"
#include <Slice/CPlusPlusUtil.h>
// #include <IceUtil/Functional.h>
#include <IceUtil/Iterator.h>
#include <Slice/Checksum.h>

// #include <limits>
// #include <sys/stat.h>

using namespace std;
using namespace slice2log;
using namespace Slice;
using namespace IceUtilInternal;

namespace detail {

void printHeader( ::IceUtilInternal::Output& out )
{
    out << "/*";
    out << "\n * Auto-generated by slice2log.";
    out << "\n * Do not modify or commit to source repository.";
    out << "\n */";
    out << "\n";
}

}

Gen::Gen(const string& name, const string& base, const string& headerExtension,
                const string& sourceExtension, const vector<string>& extraHeaders, const string& include,
                const vector<string>& includePaths, const string& dllExport, const string& dir,
                bool imp, bool checksum, bool stream, bool ice,
        // custom option
        const std::string& module) :
    _base(base),
    _headerExtension(headerExtension),
    _sourceExtension(sourceExtension),
    _extraHeaders(extraHeaders),
    _include(include),
    _includePaths(includePaths),
    _dllExport(dllExport),
    _impl(imp),
    _checksum(checksum),
    _stream(stream),
    _ice(ice),
    _module(module)
{
    for(vector<string>::iterator p = _includePaths.begin(); p != _includePaths.end(); ++p)
    {
        if(p->length() && (*p)[p->length() - 1] != '/')
        {
            *p += '/';
        }
    }

    string::size_type pos = _base.find_last_of("/\\");
    if(pos != string::npos)
    {
        _base.erase(0, pos + 1);
    }

    string fileH = _base + "." + _headerExtension;
    string fileC = _base + "." + _sourceExtension;
    if(!dir.empty())
    {
        fileH = dir + '/' + fileH;
        fileC = dir + '/' + fileC;
    }

    H.open(fileH.c_str());
    if(!H)
    {
        cerr << name << ": can't open `" << fileH << "' for writing" << endl;
        return;
    }
    
    C.open(fileC.c_str());
    if(!C)
    {
        cerr << name << ": can't open `" << fileC << "' for writing" << endl;
        return;
    }

    detail::printHeader(H);
    detail::printHeader(C);
    H << "\n// Generated from file `" << _base << ".ice'\n";
    C << "\n// Generated from file `" << _base << ".ice'\n";

    string s = fileH;
    if(_include.size())
    {
        s = _include + '/' + s;
    }
    transform(s.begin(), s.end(), s.begin(), ToIfdef());
    H << "\n#ifndef __" << s << "__";
    H << "\n#define __" << s << "__";
    H << '\n';
}

Gen::~Gen()
{
//     cout<<"DEBUG: Gen::~Gen()"<<endl;
//     H << nl << eb;
    H << "\n\n}";
    H << "\n\n#endif";
    H << '\n';

    C << '\n';
    C << "\n}";
    C << '\n';
}

bool
Gen::operator!() const
{
    if(!H || !C)
    {
        return true;
    }
    return false;
}

void
Gen::generate(const UnitPtr& p)
{    
//     cout<<"DEBUG: Gen::generate()"<<endl;
    writeExtraHeaders(C);

//     string lib_namespace = _module + "ifacelog";
    string lib_namespace = "ifacelog";
    string lib_dir = _module + "ifacelog";

    H << "\n#include <sstream>";
    H << "\n#include <" << _module << "/" << _base << ".h>";    
    // includeFiles contains full paths. we want just the base.
    StringList includes = p->includeFiles();
    for(StringList::const_iterator q = includes.begin(); q != includes.end(); ++q)
    { 
        // remove everything except the base
        string include_base = *q;
        string::size_type pos = include_base.find_last_of("/\\");
        if(pos != string::npos)
        {
            include_base.erase(0, pos + 1);
        }    
        if((pos = include_base.rfind('.')) != string::npos)
        {
            include_base.erase(pos);
        }
        // remove everything except the module
        string include_module = *q;
        string::size_type pos_mod = include_module.find_last_of("/\\");
        if(pos_mod != string::npos)
        {
            // remove base
            include_module.erase(pos_mod, string::npos);
            string::size_type pos_dir = include_module.find_last_of("/\\");
            if(pos_dir != string::npos) {
                // remove dir
                include_module.erase(0, pos_dir+1);
            }
        }    
        string include_namespace = include_module + "ifacelog";

        H << "\n#include <" << include_namespace << "/" << include_base << "." << _headerExtension << ">";
    }
    H << "\n";
    H << "\nnamespace " << lib_namespace;
    H << "\n{";
    H << "\n";

    C << "\n#include <" << lib_dir << "/" << _base << ".h>";
//     C << "\n#include <gbxutilacfr/exceptions.h>";
    C << "\n#include \"util.h\"";
    C << "\n";
    C << "\nusing namespace std;";
    C << "\n";
    C << "\nnamespace " << lib_namespace;
    C << "\n{";

    // only used to define bogus Prx functions
    HandleVisitor handleVisitor(H, C, _dllExport, _stream);
    p->visit(&handleVisitor, false);

    ToLogVisitor toLogVisitor(H, C, _dllExport, _stream);
    p->visit(&toLogVisitor, false);

    H << "\n";

    FromLogVisitor fromLogVisitor(H, C, _dllExport, _stream);
    p->visit(&fromLogVisitor, false);
}

void
Gen::writeExtraHeaders(IceUtilInternal::Output& out)
{
//     cout<<"DEBUG: Gen::writeExtraHeaders()"<<endl;
    for(vector<string>::const_iterator i = _extraHeaders.begin(); i != _extraHeaders.end(); ++i)
    {
        string hdr = *i;
        string guard;
        string::size_type pos = hdr.rfind(',');
        if(pos != string::npos)
        {
            hdr = i->substr(0, pos);
            guard = i->substr(pos + 1);
        }
        if(!guard.empty())
        {
            out << "\n#ifndef " << guard;
            out << "\n#define " << guard;
        }
        out << "\n#include <";
        if(!_include.empty())
        {
            out << _include << '/';
        }
        out << hdr << '>';
        if(!guard.empty())
        {
            out << "\n#endif";
        }
    }
}

Gen::ToLogVisitor::ToLogVisitor(Output& h, Output& c, const string& dllExport, bool stream) :
    H(h), C(c), _dllExport(dllExport), _stream(stream), _doneStaticSymbol(false), _useWstring(false)
{
}

bool
Gen::ToLogVisitor::visitModuleStart(const ModulePtr& p)
{
//     cout<<"DEBUG: Gen::visitModuleStart()"<<endl;
//     _useWstring = setUseWstring(p, _useWstringHist, _useWstring);
//     H << sp << nl << "namespace " << name << nl << '{';
    return true;
}

void
Gen::ToLogVisitor::visitModuleEnd(const ModulePtr& p)
{
//     H << sp << nl << '}';
//     _useWstring = resetUseWstring(_useWstringHist);
}

bool
Gen::ToLogVisitor::visitClassDefStart(const ClassDefPtr& p)
{
//     cout<<"DEBUG: Gen::visitClassDefStart()"<<endl;
    if ( p->declaration()->isInterface() )
        return false;

    string name = fixKwd(p->name());
    string scope = fixKwd(p->scope());
    ClassList bases = p->bases();
    
    H << "\nvoid toLogString( const " << scope.substr(2)<<name << "Ptr& obj, std::stringstream& ss );";

    C << "\n\nvoid";
    C << nl << "toLogString( const " << scope.substr(2)<<name << "Ptr& objPtr, std::stringstream& ss )";
    C << sb;

    ClassList::const_iterator q = bases.begin();
    if(!bases.empty()) {
        int count = 0;
        while(q != bases.end())
        {
            C << nl << fixKwd((*q)->scoped()) << "Ptr base" << count << "Ptr = objPtr;";
            C << nl << "toLogString( base" << count << "Ptr, ss );";
            ++q;
            ++count;
        }
    }

    if ( !p->dataMembers().empty() ) {
        C << nl;
        C << nl << scope.substr(2)<<name << "& obj = *objPtr;";
    }
    return true;
}

void
Gen::ToLogVisitor::visitClassDefEnd(const ClassDefPtr& p)
{
    C << eb;
}

bool
Gen::ToLogVisitor::visitExceptionStart(const ExceptionPtr& p)
{
    return false;
}

void
Gen::ToLogVisitor::visitExceptionEnd(const ExceptionPtr& p)
{
}

void
Gen::ToLogVisitor::visitEnum(const EnumPtr& p)
{
    string name = fixKwd(p->name());
    string scope = fixKwd(p->scope());
    EnumeratorList enumerators = p->getEnumerators();

    H << nl << "void toLogString( const " << scope.substr(2)<<name << " obj, std::stringstream& ss );";

    C << nl;
    C << nl << "void";
    C << nl << "toLogString( const " << scope.substr(2)<<name << " obj, std::stringstream& ss )";
    C << sb;
    C << nl << "toLogString( (Ice::Int)obj, ss );";
    C << eb;
}

bool
Gen::ToLogVisitor::visitStructStart(const StructPtr& p)
{
//     cout<<"DEBUG: Gen::visitStructStart()"<<endl;
    string name = fixKwd(p->name());
    string scope = fixKwd(p->scope());
    
    H << "\nvoid toLogString( const " << scope.substr(2)<<name << "& obj, std::stringstream& ss );";

    C << "\n\nvoid";
    C << nl << "toLogString( const " << scope.substr(2)<<name << "& obj, std::stringstream& ss )";
    C << sb;
    return true;
}

void
Gen::ToLogVisitor::visitStructEnd(const StructPtr& p)
{       
    C << eb;
}

void
Gen::ToLogVisitor::visitDataMember(const DataMemberPtr& p)
{
//     cout<<"DEBUG: Gen::visitDataMember()"<<endl;
    string name = fixKwd(p->name());

    C << nl << "toLogString( obj." + name + ", ss );";
}

void
Gen::ToLogVisitor::visitSequence(const SequencePtr& p)
{    
//     cout<<"DEBUG: Gen::visitSequence()"<<endl;
    string name = fixKwd(p->name());
    string scope = fixKwd(p->scope());

    H << nl << "void toLogString( const " << scope.substr(2)<<name << "& obj, std::stringstream& ss );";

    C << "\n\nvoid";
    C << nl << "toLogString( const " << scope.substr(2)<<name << "& obj, std::stringstream& ss )";
    C << sb;
    C << nl << "seqToLogString< " << scope.substr(2)<<name << " >( obj, ss );";
    C << eb;
}

void
Gen::ToLogVisitor::visitDictionary(const DictionaryPtr& p)
{
//     cout<<"DEBUG: Gen::visitDictionary()"<<endl;
    string name = fixKwd(p->name());
    string scope = fixKwd(p->scope());

    H << nl << "void toLogString( const " << scope.substr(2)<<name << "& obj, std::stringstream& ss );";

    C << nl;
    C << nl << "void";
    C << nl << "toLogString( const " << scope.substr(2)<<name << "& obj, std::stringstream& ss )";
    C << sb;
    C << nl << "dictToLogString< " << scope.substr(2)<<name << "," << scope.substr(2)<<name << "::const_iterator >( obj, ss );";
    C << eb;
}

void
Gen::ToLogVisitor::visitConst(const ConstPtr& p)
{
}

void
Gen::ToLogVisitor::emitUpcall(const ExceptionPtr& base, const string& call, bool isLocal)
{
    C.zeroIndent();
    C << nl << "#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug"; // COMPILERBUG
    C.restoreIndent();
    C << nl << (base ? fixKwd(base->name()) : string(isLocal ? "LocalException" : "UserException")) << call;
    C.zeroIndent();
    C << nl << "#else";
    C.restoreIndent();
    C << nl << (base ? fixKwd(base->scoped()) : string(isLocal ? "::Ice::LocalException" : "::Ice::UserException")) 
      << call;
    C.zeroIndent();
    C << nl << "#endif";
    C.restoreIndent();
}

///////

Gen::FromLogVisitor::FromLogVisitor(Output& h, Output& c, const string& dllExport, bool stream) :
    H(h), C(c), _dllExport(dllExport), _stream(stream), _doneStaticSymbol(false), _useWstring(false)
{
}

bool
Gen::FromLogVisitor::visitModuleStart(const ModulePtr& p)
{
//     cout<<"DEBUG: Gen::visitModuleStart()"<<endl;
//     _useWstring = setUseWstring(p, _useWstringHist, _useWstring);
//     H << sp << nl << "namespace " << name << nl << '{';
    return true;
}

void
Gen::FromLogVisitor::visitModuleEnd(const ModulePtr& p)
{
//     H << sp << nl << '}';
//     _useWstring = resetUseWstring(_useWstringHist);
}

bool
Gen::FromLogVisitor::visitClassDefStart(const ClassDefPtr& p)
{
//     cout<<"DEBUG: Gen::visitClassDefStart()"<<endl;
    if ( p->declaration()->isInterface() )
        return false;

    string name = fixKwd(p->name());
    string scope = fixKwd(p->scope());
    ClassList bases = p->bases();
    
    H << "\nvoid fromLogString( " << scope.substr(2)<<name << "Ptr& obj, std::stringstream& ss );";

    C << "\n\nvoid";
    C << nl << "fromLogString( " << scope.substr(2)<<name << "Ptr& objPtr, std::stringstream& ss )";
    C << sb;

    ClassList::const_iterator q = bases.begin();
    if(!bases.empty()) {
        int count = 0;
        while(q != bases.end())
        {
            C << nl << fixKwd((*q)->scoped()) << "Ptr base" << count << "Ptr = objPtr;";
            C << nl << "toLogString( base" << count << "Ptr, ss );";
            ++q;
            ++count;
        }
    }

    if ( !p->dataMembers().empty() ) {
        C << nl;
        C << nl << scope.substr(2)<<name << "& obj = *objPtr;";
    }
    return true;
}

void
Gen::FromLogVisitor::visitClassDefEnd(const ClassDefPtr& p)
{
    C << eb;
}

bool
Gen::FromLogVisitor::visitExceptionStart(const ExceptionPtr& p)
{
    return false;
}

void
Gen::FromLogVisitor::visitExceptionEnd(const ExceptionPtr& p)
{
}

void
Gen::FromLogVisitor::visitEnum(const EnumPtr& p)
{
    string name = fixKwd(p->name());
    string scope = fixKwd(p->scope());
    EnumeratorList enumerators = p->getEnumerators();

    H << nl << "void fromLogString( " << scope.substr(2)<<name << "& obj, std::stringstream& ss );";

    C << nl;
    C << nl << "void";
    C << nl << "fromLogString( " << scope.substr(2)<<name << "& obj, std::stringstream& ss )";
    C << sb;
    C << nl << "Ice::Int i;";
    C << nl << "fromLogString( i, ss );";
    C << nl << "obj =  (" << scope.substr(2)<<name << ")i;";
    C << eb;
}

bool
Gen::FromLogVisitor::visitStructStart(const StructPtr& p)
{
//     cout<<"DEBUG: Gen::visitStructStart()"<<endl;
    string name = fixKwd(p->name());
    string scope = fixKwd(p->scope());
    
    H << "\nvoid fromLogString( " << scope.substr(2)<<name << "& obj, std::stringstream& ss );";

    C << "\n\nvoid";
    C << nl << "fromLogString( " << scope.substr(2)<<name << "& obj, std::stringstream& ss )";
    C << sb;
    return true;
}

void
Gen::FromLogVisitor::visitStructEnd(const StructPtr& p)
{       
    C << eb;
}

void
Gen::FromLogVisitor::visitDataMember(const DataMemberPtr& p)
{
//     cout<<"DEBUG: Gen::visitDataMember()"<<endl;
    string name = fixKwd(p->name());

    C << nl << "fromLogString( obj." + name + ", ss );";
}

void
Gen::FromLogVisitor::visitSequence(const SequencePtr& p)
{    
//     cout<<"DEBUG: Gen::visitSequence()"<<endl;
    string name = fixKwd(p->name());

    TypePtr type = p->type();
    string s = typeToString(type, _useWstring, p->typeMetaData());
    StringList metaData = p->getMetaData();
    string seqType = findMetaData(metaData, false);
    string es;
    if(!seqType.empty())
    {
        es = seqType;
    }
    else
    {
        es = (s[0] == ':' ? " " : "") + s;
    }

    string scope = fixKwd(p->scope());

    H << nl << "void fromLogString( " << scope.substr(2)<<name << "& obj, std::stringstream& ss );";

    C << "\n\nvoid";
    C << nl << "fromLogString( " << scope.substr(2)<<name << "& obj, std::stringstream& ss )";
    C << sb;
    C << nl << "seqFromLogString<"<<es<<">( obj, ss );";
    C << eb;
}

void
Gen::FromLogVisitor::visitDictionary(const DictionaryPtr& p)
{
    string name = fixKwd(p->name());

    TypePtr keyType = p->keyType();
    TypePtr valueType = p->valueType();
    string ks = typeToString(keyType, _useWstring, p->keyMetaData());
    if(ks[0] == ':')
    {
        ks.insert(0, " ");
    }
    string vs = typeToString(valueType, _useWstring, p->valueMetaData());

    string scope = fixKwd(p->scope());

    H << nl << "void fromLogString( " << scope.substr(2)<<name << "& obj, std::stringstream& ss );";

    C << nl;
    C << nl << "void";
    C << nl << "fromLogString( " << scope.substr(2)<<name << "& obj, std::stringstream& ss )";
    C << sb;
    C << nl << "dictFromLogString<"<<ks<<","<<vs<<">( obj, ss );";
    C << eb;
}

void
Gen::FromLogVisitor::visitConst(const ConstPtr& p)
{
}

void
Gen::FromLogVisitor::emitUpcall(const ExceptionPtr& base, const string& call, bool isLocal)
{
    C.zeroIndent();
    C << nl << "#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug"; // COMPILERBUG
    C.restoreIndent();
    C << nl << (base ? fixKwd(base->name()) : string(isLocal ? "LocalException" : "UserException")) << call;
    C.zeroIndent();
    C << nl << "#else";
    C.restoreIndent();
    C << nl << (base ? fixKwd(base->scoped()) : string(isLocal ? "::Ice::LocalException" : "::Ice::UserException")) 
      << call;
    C.zeroIndent();
    C << nl << "#endif";
    C.restoreIndent();
}

//////////

Gen::HandleVisitor::HandleVisitor(Output& h, Output& c, const string& dllExport, bool stream) :
    H(h), C(c), _dllExport(dllExport), _stream(stream)
{
}

bool
Gen::HandleVisitor::visitModuleStart(const ModulePtr& p)
{
    C << sp;
    C << nl << "namespace " << nl << '{';

    return true;
}

void
Gen::HandleVisitor::visitModuleEnd(const ModulePtr& p)
{
    C << sp;
    C << nl << '}';
}

void
Gen::HandleVisitor::visitClassDecl(const ClassDeclPtr& p)
{
    string name = p->name();
    string scoped = fixKwd(p->scoped());

    if(!p->isLocal())
    {
        C << nl << "void toLogString( const " << scoped << "Prx& prx, std::stringstream& ss )";
        C << sb;
        C << nl << "// this data is not logged.";
        C << eb;

        C << nl << "void fromLogString( " << scoped << "Prx& prx, std::stringstream& ss )";
        C << sb;
        C << nl << "// this data is not logged.";
        C << eb;
    }
}

bool
Gen::HandleVisitor::visitClassDefStart(const ClassDefPtr& p)
{
    return true;
}

bool
Gen::setUseWstring(ContainedPtr p, list<bool>& hist, bool use)
{
    hist.push_back(use);
    StringList metaData = p->getMetaData();
    if(find(metaData.begin(), metaData.end(), "cpp:type:wstring") != metaData.end())
    {
        use = true;
    }
    else if(find(metaData.begin(), metaData.end(), "cpp:type:string") != metaData.end())
    {
        use = false;
    }
    return use;
}

bool
Gen::resetUseWstring(list<bool>& hist)
{
    bool use = hist.back();
    hist.pop_back();
    return use;
}
