#!/bin/sh
#
# Update from cvs, and rebuild the docco.
# If nothing has changed, just exit.
#
#

forced=0
if [ $# -eq 1 ]
then
    if [ $1 = "-f" -o $1 = "--force" ]
    then
        forced=1
    fi
fi

DOXYGENCMD=/usr/local/bin/doxyorca
DOXYFILE=doxyfile
#  CVS 
#UPDATECMD="cvs update"
#CHANGESIGN="'^[UP]'"
#  SVN
UPDATECMD="svn update --non-interactive"
CHANGESIGN='^[U]'
# source
PROJDIR=$HOME/svn/docversion/orca
MODULENAME=orca
TARBALL=$MODULENAME-head-doc.tar.gz
# destination
HEADDIR=/home/groups/o/or/orca-robotics/htdocs/head_doc

did_update=0

date

#
# Update project
#
if ! cd $PROJDIR 2>&1; then
    echo "Problem changing to directory $PROJDIR"
    exit 1
fi
pwd
if $UPDATECMD 2>&1 | egrep -e $CHANGESIGN 2>&1; then
    echo "Project has changed."
    did_update=1
fi

#
# Exit if we are not forced and nothing changed
#
if [ $did_update -eq 0 ]; then
    if [ $forced -eq 1 ]; then
        echo "Forced to rebuild docs -- even though nothing changed."
    else
        echo "No need to rebuild docs -- nothing changed."
        exit 0;
    fi
fi

#
# Rebuild docco
#
cd $PROJDIR/doc
$DOXYGENCMD $DOXYFILE
cat html/index.html | sed "s/Generated for Orca Robotics/Generated for Orca Robotics (on `date`)/" > temp_index.html
mv temp_index.html html/index.html

#
# Copy it to sourceforge
#
rm -rf $MODULENAME
mv html $MODULENAME
tar -zcvf $TARBALL $MODULENAME
echo "scp $TARBALL shell.sf.net:$HEADDIR/."
scp  $TARBALL shell.sf.net:$HEADDIR/.
echo "ssh shell.sf.net 'cd $HEADDIR; tar -zxf $TARBALL'"
ssh shell.sf.net "cd $HEADDIR; tar -zxf $TARBALL"

echo "Finished $0 at: `date`"
