#!/bin/sh
#
# Update from cvs, and rebuild the docco.
# If nothing has changed, just exit.
#
#

DOXYGENCMD=/usr/local/bin/doxyorca
#  CVS 
#UPDATECMD="cvs update"
#CHANGESIGN="'^[UP]'"
#  SVN
UPDATECMD="svn update --non-interactive"
CHANGESIGN="'^[U]'"
HTDOCS=/home/groups/o/or/orca-robotics/htdocs
PROJDIR=$HOME/cvs/docversion/orca2
TARBALL=orca-cvs-doc.tar.gz

did_update=0

date

#
# Update project
#
if ! cd $PROJDIR 2>&1; then
    echo "Problem changing to directory $PROJDIR"
    exit 1
fi
pwd
if $UPDATECMD 2>&1 | egrep -e $CHANGESIGN 2>&1; then
    echo "Project has changed."
    did_update=1
fi

#
# Exit if nothing changed
#
if [ $did_update -eq 0 ]; then
    echo "No need to rebuild docs -- nothing changed."
    exit 0;
fi

#
# Rebuild docco
#
cd $PROJDIR/doc
$DOXYGENCMD orca.doxyfile
cat html/index.html | sed "s/Generated for Orca Robotics/Generated for Orca Robotics (on `date`)/" > temp_index.html
mv temp_index.html html/index.html

#
# Copy it to sourceforge
#
tar -zcvf $TARBALL html
scp  $TARBALL shell.sf.net:$HTDOCS/cvs_version/orca2/doc/
ssh shell.sf.net "cd $HTDOCS/cvs_version/orca2/doc/; tar -zxvf $TARBALL"

echo "Finished $0 at: `date`"
