# Locate Gearbox installation

# This module defines
# VELODYNE_HOME where to find include, lib, bin, etc.
# VELODYNE_FOUND, If set to 0, don't try to use Gearbox libraries, scripts, etc.
#
# We look for the cmake manifest file generated by Gearbox.

# start with 'not found'
set( VELODYNE_FOUND 0 CACHE BOOL "Do we have Velodyne?" )

find_path( VELODYNE_HOME velodyne_manifest.cmake
# Test user-specified installation point (first look in the dir specified
# with command line CMake variable, then with environment variable)
    ${VELODYNE_HOME}
    $ENV{VELODYNE_HOME}
# Test standard installation points
    /usr/local
    /opt/velodyne
)
message( STATUS "DEBUG: Velodyne manifest found in : ${VELODYNE_HOME}" )

# NOTE: if VELODYNE_HOME is set to *-NOTFOUND it will evaluate to FALSE
if( VELODYNE_HOME )
    set( VELODYNE_FOUND 1 CACHE BOOL "Do we have Velodyne?" FORCE )
endif( VELODYNE_HOME )
