/*
 * Orca-Robotics Project: Components for robotics 
 *               http://orca-robotics.sf.net/
 * Copyright (c) 2004-2007 NovAtel Inc.
 *
 * This copy of Orca is licensed to you under the terms described in
 * the LICENSE file included in this distribution.
 *
 */

#ifndef _CMDTYPES_H_
#define _CMDTYPES_H_

namespace novatel{

    enum BINARY_CMD_TYPE{

	ADJUST1PPS_CMD_TYPE=429,
	ANTENNAPOWER_CMD_TYPE=98,
	ASSIGN_CMD_TYPE=27,
	ASSIGNALL_CMD_TYPE=28,
	ASSIGNLBAND_CMD_TYPE=729,
	AUTH_CMD_TYPE=49,
	CLOCKADJUST_CMD_TYPE=15,
	CLOCKCALIBRATE_CMD_TYPE=430,
	CLOCKOFFSET_CMD_TYPE=569,
	COM_CMD_TYPE=4,
	COMCONTROL_CMD_TYPE=431,
	CSMOOTH_CMD_TYPE=269,
	DATUM_CMD_TYPE=160,
	DGPSEPHEMDELAY_CMD_TYPE=142,
	DGPSTIMEOUT_CMD_TYPE=127,
	DGPSTXID_CMD_TYPE=144,
	DYNAMICS_CMD_TYPE=258,
	ECUTOFF_CMD_TYPE=50,
	EXTERNALCLOCK_CMD_TYPE=230,
	FIX_CMD_TYPE=44,
	FREQUENCYOUT_CMD_TYPE=232,
	FRESET_CMD_TYPE=20,
	GGAQUALITY_CMD_TYPE=691,
	INTERFACEMODE_CMD_TYPE=3,
	LOCKOUT_CMD_TYPE=137,
	LOG_CMD_TYPE=1,
	MAGVAR_CMD_TYPE=180,
        MARKCONTROL_CMD_TYPE=614,
        MODEL_CMD_TYPE=22,
        NVMRESTORE_CMD_TYPE=197,
        POSAVE_CMD_TYPE=173,
        PPSCONTROL_CMD_TYPE=613,
        PSRDIFFSOURCE_CMD_TYPE=493,
        RESET_CMD_TYPE=18,
        RTKBASELINE_CMD_TYPE=182,
        RTKCOMMAND_CMD_TYPE=97,
        RTKDYNAMICS_CMD_TYPE=183,
        RTKELEVMASK_CMD_TYPE=91,
        RTKSOLUTION_CMD_TYPE=184,
        RTKSOURCE_CMD_TYPE=494,
        RTKSVENTRIES_CMD_TYPE=92,
        SAVECONFIG_CMD_TYPE=19,
        SBASCONTROL_CMD_TYPE=652,
        SEND_CMD_TYPE=177,
        SENDHEX_CMD_TYPE=178,
        SETAPPROXPOS_CMD_TYPE=377,
        SETAPPROXTIME_CMD_TYPE=102,
        SETNAV_CMD_TYPE=162,
        SETRTCM16_CMD_TYPE=131,
        STATUSCONFIG_CMD_TYPE=95,
        UNASSIGN_CMD_TYPE=29,
        UNASSIGNALL_CMD_TYPE=30,
        UNDULATION_CMD_TYPE=214,
        UNLOCKOUT_CMD_TYPE=138,
        UNLOCKOUTALL_CMD_TYPE=139,
        UNLOG_CMD_TYPE=36,
        UNLOGALL_CMD_TYPE=38,
	USERDATUM_CMD_TYPE=78,

        //INS commands
        INSCOMMAND_CMD_TYPE=379,
        INSINITRTK_CMD_TYPE=380,
        INSPHASEUPDATE_CMD_TYPE=639,
        INSZUPT_CMD_TYPE=382,
        LEVERARMCALIBRATE_CMD_TYPE=675,
        RVBCALIBRATE_CMD_TYPE=641,
        SETIMUORIENTATION_CMD_TYPE=567,
        SETIMUTOANTOFFSET_CMD_TYPE=383,
        SETIMUTYPE_CMD_TYPE=569,
        SETINSOFFSET_CMD_TYPE=676,
        VEHICLEBODYROTATION_CMD_TYPE=642,
    };
    typedef enum BINARY_CMD_TYPE BINARY_CMD_TYPE;
    
}



#endif
