INCLUDE_DIRECTORIES( ${GEARBOX_HOME}/include/gearbox )
LINK_DIRECTORIES( ${GEARBOX_HOME}/lib/gearbox )

INCLUDE_DIRECTORIES( ${HYDRO_HOME}/include )
LINK_DIRECTORIES( ${HYDRO_HOME}/lib )

LINK_LIBRARIES( GbxUtilAcfr HydroUtil )
