INCLUDE_DIRECTORIES( 
    ${PROJECT_BINARY_DIR}/src/interfaces/cpp
)

LINK_DIRECTORIES(
    ${PROJECT_BINARY_DIR}/src/interfaces/cpp/orca
)

#
# Platform-specific compiler and linker flags
#
IF ( NOT OS_WIN )
    LINK_LIBRARIES( ${PROJECT_INTERFACE_LIB} )

    FILE( GLOB SRCS *.cpp )
    FOREACH( SLICE_GENERATED_HEADER ${SLICE_GENERATED_HEADER_FILES} )
        SET_SOURCE_FILES_PROPERTIES( ${SRCS} PROPERTIES OBJECT_DEPENDS ${SLICE_GENERATED_HEADER_FILES} )
    ENDFOREACH( SLICE_GENERATED_HEADER )

ELSE ( NOT OS_WIN )
    # windows... have to link to different libs depending on build type
    LINK_LIBRARIES( ${PROJECT_INTERFACE_LIB} )

    FILE( GLOB SRCS *.cpp )
    FOREACH( SLICE_GENERATED_HEADER ${SLICE_GENERATED_HEADER_FILES} )
        SET_SOURCE_FILES_PROPERTIES( ${SRCS} PROPERTIES OBJECT_DEPENDS ${SLICE_GENERATED_HEADER_FILES} )
    ENDFOREACH( SLICE_GENERATED_HEADER )

ENDIF ( NOT OS_WIN )
