#
# Include and link against Qt core and gui libs
#
INCLUDE_DIRECTORIES( ${PLAYER_INCLUDE_DIRS} )

LINK_DIRECTORIES( ${PLAYER_LINK_DIRS} )

ADD_DEFINITIONS( ${PLAYER_DEFINITIONS} )

LINK_LIBRARIES( ${QT_QTGUI_LIBRARY} ${QT_QTCORE_LIBRARY} )

