#
# writes file ${global_header_file} which includes all header files in the list assuming that
# they are located in the specified directory.
#
MACRO( WRITE_GLOBAL_HEADER_FILE global_header_file header_file_dir define_name )

    MESSAGE( STATUS "Generating global header file ${global_header_file}" )
    WRITE_FILE( ${global_header_file} "/*" ) # <-- not appending!
    WRITE_FILE( ${global_header_file} " * Auto-generated by CMake." APPEND )
    WRITE_FILE( ${global_header_file} " * Do not modify or commit to source repository." APPEND )
    WRITE_FILE( ${global_header_file} " */" APPEND )
    WRITE_FILE( ${global_header_file} "" APPEND )
    WRITE_FILE( ${global_header_file} "#ifndef ${define_name}" APPEND )
    WRITE_FILE( ${global_header_file} "#define ${define_name}" APPEND )
    WRITE_FILE( ${global_header_file} "" APPEND )

    FOREACH ( header_file ${ARGN} )
        WRITE_FILE( ${global_header_file} "#include <${header_file_dir}/${header_file}>" APPEND )
    ENDFOREACH ( header_file ${ARGN} )

    WRITE_FILE( ${global_header_file} "" APPEND )
    WRITE_FILE( ${global_header_file} "#endif" APPEND )

ENDMACRO( WRITE_GLOBAL_HEADER_FILE global_header_file header_file_dir define_name )
